// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_auth_any_forgot_password from "./routes/(auth)/(any)/forgot-password.tsx";
import * as $_auth_any_reset_password_index from "./routes/(auth)/(any)/reset-password/index.tsx";
import * as $_auth_any_reset_password_verify_email from "./routes/(auth)/(any)/reset-password/verify-email.tsx";
import * as $_auth_authenticated_2fa_passkey from "./routes/(auth)/(authenticated)/2fa/passkey.tsx";
import * as $_auth_authenticated_middleware from "./routes/(auth)/(authenticated)/_middleware.ts";
import * as $_auth_authenticated_logout from "./routes/(auth)/(authenticated)/logout.tsx";
import * as $_auth_authenticated_verify_email_resend from "./routes/(auth)/(authenticated)/verify-email-resend.ts";
import * as $_auth_authenticated_verify_email from "./routes/(auth)/(authenticated)/verify-email.tsx";
import * as $_auth_guest_middleware from "./routes/(auth)/(guest)/_middleware.ts";
import * as $_auth_guest_login from "./routes/(auth)/(guest)/login.tsx";
import * as $_auth_guest_login_passkey from "./routes/(auth)/(guest)/login/passkey.ts";
import * as $_auth_guest_signup from "./routes/(auth)/(guest)/signup.tsx";
import * as $_user_slug_middleware from "./routes/[user]/[slug]/_middleware.ts";
import * as $_user_slug_edit_entry_ from "./routes/[user]/[slug]/edit/[entry].tsx";
import * as $_user_slug_index from "./routes/[user]/[slug]/index.tsx";
import * as $_user_slug_write from "./routes/[user]/[slug]/write.tsx";
import * as $_user_middleware from "./routes/[user]/_middleware.ts";
import * as $_user_index from "./routes/[user]/index.tsx";
import * as $_user_start from "./routes/[user]/start.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_files_download_index from "./routes/api/files/download/index.ts";
import * as $api_files_upload_index from "./routes/api/files/upload/index.ts";
import * as $api_files_upload_local from "./routes/api/files/upload/local.ts";
import * as $api_webauthn_challenge_login from "./routes/api/webauthn/challenge/login.ts";
import * as $api_webauthn_challenge_register from "./routes/api/webauthn/challenge/register.ts";
import * as $index from "./routes/index.tsx";
import * as $auth_login_with_passkey_button from "./islands/auth/login-with-passkey-button.tsx";
import * as $auth_register_passkey_button from "./islands/auth/register-passkey-button.tsx";
import * as $content_editor_content_editor from "./islands/content-editor/content-editor.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(auth)/(any)/forgot-password.tsx": $_auth_any_forgot_password,
    "./routes/(auth)/(any)/reset-password/index.tsx":
      $_auth_any_reset_password_index,
    "./routes/(auth)/(any)/reset-password/verify-email.tsx":
      $_auth_any_reset_password_verify_email,
    "./routes/(auth)/(authenticated)/2fa/passkey.tsx":
      $_auth_authenticated_2fa_passkey,
    "./routes/(auth)/(authenticated)/_middleware.ts":
      $_auth_authenticated_middleware,
    "./routes/(auth)/(authenticated)/logout.tsx": $_auth_authenticated_logout,
    "./routes/(auth)/(authenticated)/verify-email-resend.ts":
      $_auth_authenticated_verify_email_resend,
    "./routes/(auth)/(authenticated)/verify-email.tsx":
      $_auth_authenticated_verify_email,
    "./routes/(auth)/(guest)/_middleware.ts": $_auth_guest_middleware,
    "./routes/(auth)/(guest)/login.tsx": $_auth_guest_login,
    "./routes/(auth)/(guest)/login/passkey.ts": $_auth_guest_login_passkey,
    "./routes/(auth)/(guest)/signup.tsx": $_auth_guest_signup,
    "./routes/[user]/[slug]/_middleware.ts": $_user_slug_middleware,
    "./routes/[user]/[slug]/edit/[entry].tsx": $_user_slug_edit_entry_,
    "./routes/[user]/[slug]/index.tsx": $_user_slug_index,
    "./routes/[user]/[slug]/write.tsx": $_user_slug_write,
    "./routes/[user]/_middleware.ts": $_user_middleware,
    "./routes/[user]/index.tsx": $_user_index,
    "./routes/[user]/start.tsx": $_user_start,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/files/download/index.ts": $api_files_download_index,
    "./routes/api/files/upload/index.ts": $api_files_upload_index,
    "./routes/api/files/upload/local.ts": $api_files_upload_local,
    "./routes/api/webauthn/challenge/login.ts": $api_webauthn_challenge_login,
    "./routes/api/webauthn/challenge/register.ts":
      $api_webauthn_challenge_register,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/auth/login-with-passkey-button.tsx":
      $auth_login_with_passkey_button,
    "./islands/auth/register-passkey-button.tsx": $auth_register_passkey_button,
    "./islands/content-editor/content-editor.tsx":
      $content_editor_content_editor,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
