// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_auth_forgot_password from "./routes/(auth)/forgot-password.tsx";
import * as $_auth_login from "./routes/(auth)/login.tsx";
import * as $_auth_reset_password_index from "./routes/(auth)/reset-password/index.tsx";
import * as $_auth_reset_password_verify_email from "./routes/(auth)/reset-password/verify-email.tsx";
import * as $_auth_signout from "./routes/(auth)/signout.tsx";
import * as $_auth_signup from "./routes/(auth)/signup.tsx";
import * as $_auth_verify from "./routes/(auth)/verify.tsx";
import * as $_slug_ from "./routes/[slug].tsx";
import * as $_slug_edit_entryId_ from "./routes/[slug]/edit/[entryId].tsx";
import * as $_slug_write from "./routes/[slug]/write.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_files_download_index from "./routes/api/files/download/index.ts";
import * as $api_files_upload_index from "./routes/api/files/upload/index.ts";
import * as $api_files_upload_local from "./routes/api/files/upload/local.ts";
import * as $index from "./routes/index.tsx";
import * as $journals from "./routes/journals.tsx";
import * as $start from "./routes/start.tsx";
import * as $content_editor_content_editor from "./islands/content-editor/content-editor.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(auth)/forgot-password.tsx": $_auth_forgot_password,
    "./routes/(auth)/login.tsx": $_auth_login,
    "./routes/(auth)/reset-password/index.tsx": $_auth_reset_password_index,
    "./routes/(auth)/reset-password/verify-email.tsx":
      $_auth_reset_password_verify_email,
    "./routes/(auth)/signout.tsx": $_auth_signout,
    "./routes/(auth)/signup.tsx": $_auth_signup,
    "./routes/(auth)/verify.tsx": $_auth_verify,
    "./routes/[slug].tsx": $_slug_,
    "./routes/[slug]/edit/[entryId].tsx": $_slug_edit_entryId_,
    "./routes/[slug]/write.tsx": $_slug_write,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/files/download/index.ts": $api_files_download_index,
    "./routes/api/files/upload/index.ts": $api_files_upload_index,
    "./routes/api/files/upload/local.ts": $api_files_upload_local,
    "./routes/index.tsx": $index,
    "./routes/journals.tsx": $journals,
    "./routes/start.tsx": $start,
  },
  islands: {
    "./islands/content-editor/content-editor.tsx":
      $content_editor_content_editor,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
